# Generated by Django 6.0.6 on 2026-06-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenges_solved',
            field=models.TextField(blank=True, help_text='Key engineering challenges solved during development', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='implementation_details',
            field=models.TextField(blank=True, help_text='Detailed description of features and modules', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='key_learnings',
            field=models.TextField(blank=True, help_text='Major technical learnings and takeaways', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, help_text='Comma-separated tech tags (e.g. React, Django, PostgreSQL)', max_length=500, null=True),
        ),
    ]
