# Generated by Django 6.0.6 on 2026-06-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_challenges_solved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiter_name', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('requested_date', models.DateTimeField(help_text='Tentative date and time for the interview')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
